### PR TITLE
Fix/issue 35 exc bad access

### PR DESCRIPTION
**Pull request by doronkatz**
Fix issue #35 which was caused due to a an animation added in commit b46e53a35aa4053df085af10bd72cf29b2ba4fa7.

### CODE REVIEW

**Comment by Dimillian** [comment]
I can see a lot of unrelated script + it removes some functionalities from the app. Are you sure your MR have been opened correctly?

**Comment by doronkatz** [comment]
> Apologies I may have had my branch contaminated.  Yeah please roll back those if you want. 


Thanks 

This email and any attachments are confidential and may be subject to copyright, legal or some other professional privilege.
They are intended solely for the attention and use of the named addressee(s). They may only be copied, distributed or
disclosed with the consent of the copyright owner. If you have received this email by mistake or by breach of the confidentiality
clause, please notify the sender immediately by return email and delete or destroy all copies of the email. Any confidentiality,
privilege or copyright is not waived or lost because this email has been sent to you by mistake.

**Comment by doronkatz** [comment]
Reverted other non-related changes inadvertently included in original PR request

**Comment by Dimillian** [comment]
This is crazy, but it does indeed fix a bunch of crashes when navigating in the stack. Now I wonder why.

**Pull request merged**
